//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class AllBookDB : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _BookName;
		public string BookName { get { return _BookName; } }

		[SerializeField]
		private string _Genre;
		public string Genre { get { return _Genre; } }

		[SerializeField]
		private string _Contents;
		public string Contents { get { return _Contents; } }

		[SerializeField]
		private int _Price;
		public int Price { get { return _Price; } }


		public AllBookDB()
		{
		}

#if UNITY_EDITOR
		public AllBookDB(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _BookName);
			TryParse(sheet[row][column++], out _Genre);
			TryParse(sheet[row][column++], out _Contents);
			TryParse(sheet[row][column++], out _Price);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class Book_AllBookDB_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<AllBookDB> elements = new List<AllBookDB>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as AllBookDB);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
